# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaixasAPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50)),
                ('disponibilidade', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataBaixa', models.DateTimeField(default=django.utils.timezone.now)),
                ('valorPago', models.CharField(max_length=14)),
                ('residual', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='BaixasAReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=50)),
                ('disponibilidade', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataBaixa', models.DateTimeField(default=django.utils.timezone.now)),
                ('valorPago', models.CharField(max_length=14)),
                ('residual', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContasBancarias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=18)),
                ('descricao', models.CharField(max_length=50)),
                ('numeroConta', models.CharField(max_length=20)),
                ('numeroAgencia', models.CharField(max_length=20)),
                ('dataSaldoInicial', models.CharField(max_length=12)),
                ('saldoInicial', models.CharField(max_length=14)),
                ('caixa', models.CharField(max_length=1)),
                ('banco', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Endereco')),
            ],
        ),
        migrations.CreateModel(
            name='FormasDePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentosAPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVencimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataEmissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('valorTitulo', models.CharField(max_length=14)),
                ('numeroDocumento', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Empresas')),
            ],
        ),
        migrations.CreateModel(
            name='LancamentosAReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVencimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataEmissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('valorTitulo', models.CharField(max_length=14)),
                ('numeroDocumento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeContas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=18)),
                ('tipoConta', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('entradaSaida', models.CharField(max_length=50)),
                ('contaBancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.ContasBancarias')),
            ],
        ),
        migrations.CreateModel(
            name='Tesouraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=14)),
                ('numero', models.CharField(max_length=15)),
                ('dataEmissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataVencimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataDisponibilidade', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=20)),
                ('nomeCompleto', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePessoaFisica',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.Cliente')),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=18)),
                ('funcao', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Endereco')),
            ],
            bases=('financas.cliente',),
        ),
        migrations.CreateModel(
            name='ClientePessoaJuridica',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.Cliente')),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=18)),
                ('funcao', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Endereco')),
            ],
            bases=('financas.cliente',),
        ),
        migrations.CreateModel(
            name='FornecedorPessoaFisica',
            fields=[
                ('fornecedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.Fornecedor')),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=18)),
                ('funcao', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Endereco')),
            ],
            bases=('financas.fornecedor',),
        ),
        migrations.CreateModel(
            name='FornecedorPessoaJuridica',
            fields=[
                ('fornecedor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.Fornecedor')),
                ('identificacao', models.CharField(max_length=50)),
                ('classificacao', models.CharField(max_length=18)),
                ('funcao', models.CharField(max_length=50)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Endereco')),
            ],
            bases=('financas.fornecedor',),
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.Pessoa')),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Endereco')),
            ],
            bases=('financas.pessoa',),
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='financas.Pessoa')),
                ('razaoSocial', models.CharField(max_length=200)),
                ('inscricaoEstadual', models.CharField(max_length=50)),
                ('inscricaoMunicipal', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=20)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Endereco')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.PessoaFisica')),
            ],
            bases=('financas.pessoa',),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Cliente'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Empresas'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='formaDePagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.FormasDePagamento'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Fornecedor'),
        ),
        migrations.AddField(
            model_name='tesouraria',
            name='planoDeContas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.PlanoDeContas'),
        ),
        migrations.AddField(
            model_name='lancamentosareceber',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Cliente'),
        ),
        migrations.AddField(
            model_name='lancamentosareceber',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Empresas'),
        ),
        migrations.AddField(
            model_name='lancamentosapagar',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.Fornecedor'),
        ),
        migrations.AddField(
            model_name='baixasareceber',
            name='formaDePagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.FormasDePagamento'),
        ),
        migrations.AddField(
            model_name='baixasareceber',
            name='lancamentosAReceber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.LancamentosAReceber'),
        ),
        migrations.AddField(
            model_name='baixasapagar',
            name='formaDePagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.FormasDePagamento'),
        ),
        migrations.AddField(
            model_name='baixasapagar',
            name='lancamentosAPagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.LancamentosAPagar'),
        ),
        migrations.AddField(
            model_name='fornecedorpessoajuridica',
            name='pessoaJuridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.PessoaJuridica'),
        ),
        migrations.AddField(
            model_name='fornecedorpessoafisica',
            name='pessoaFisica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='pessoaJuridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.PessoaJuridica'),
        ),
        migrations.AddField(
            model_name='clientepessoajuridica',
            name='pessoaJuridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.PessoaJuridica'),
        ),
        migrations.AddField(
            model_name='clientepessoafisica',
            name='pessoaFisica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.PessoaFisica'),
        ),
    ]
