# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_auto_20170424_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
