# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0010_remove_pessoa_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
